version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: psk-proxy-server:local
    container_name: psk-proxy-server
    env_file: .env.docker
    ports:
      - "8102:8000"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --forwarded-allow-ips='*'
