name: Build and Push to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |-
          echo "Building Docker image..."
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/psk-proxy-server:${{ github.sha }} .
          
          echo "Pushing to Google Container Registry..."
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/psk-proxy-server:${{ github.sha }}
